export type UserRole =
  | 'STUDENT'
  | 'FACULTY_MENTOR'
  | 'PROGRAM_ADMIN'
  | 'TRAINER'
  | 'PLACEMENT_COORDINATOR'
  | 'SUPER_ADMIN'
  | 'PLATFORM_OWNER';

export const STAFF_ROLES: UserRole[] = [
  'FACULTY_MENTOR',
  'PROGRAM_ADMIN',
  'TRAINER',
  'PLACEMENT_COORDINATOR',
];

export const ADMIN_ROLES: UserRole[] = ['SUPER_ADMIN', 'PLATFORM_OWNER'];
